### PR TITLE
Moved "Taken Exams" to a filter under Exam Registration

### PR DESCRIPTION
**Pull request by FeaXR**
In my previous PR I modified the full js file, now I recreated it in the modules.

I found it useful, might as well share with others. 
Moved the "Taken Exams" to a filter in Exam Registration, renamed the Exams button to be more accurate and removed the dropdown list as it's now not needed

### CODE REVIEW

**Comment by solymosi** [comment]
Thanks for the contribution, I'll review it as soon as possible.

**Comment by solymosi** [comment]
Please run Prettier on the file:

```Checking formatting...
[warn] src/modules/examListFixes.js
[warn] Code style issues found in the above file(s). Forgot to run Prettier?

**Comment by FeaXR** [comment]
I ran Prettier on the file before PR, and reran it now, but the file remained unchanged. GitHub desktop gave a warning for not having a blank line at the EOF, so added it manually.

**Comment by FeaXR** [comment]
Sadly I have no idea where the problem is, and I don't seem to be able to recreate the whole build environment on my machine.
Would you be so kind and run your setup of Prettier on the problematic file?

**Comment by FeaXR** [comment]
@solymosi All checks hava passed, does that mean that my PR will be accepted?

**Comment by solymosi** [comment]
@FeaXR I tested your changes and they look good. However, we cannot hide the "subscribed exams" page in the menu because it also shows exams of past semesters, whereas the exam subscription page does not. Users would lose access to important information if they couldn't access the subscribed exams page.

I will make a few more minor changes to this PR and then merge it 👍

**Comment by FeaXR** [comment]
@solymosi  Thank you! I did not think of that, as I never had to use that functionality.

**Comment by solymosi** [comment]
I had to add some changes to I'm closing this in favor of #70

**Comment by solymosi** [comment]
Released in 2.3.0 🎉 – thanks again for your contribution 👍

**Pull request closed without merging**
