### PR TITLE
Hide header fix for #73

### PR DESCRIPTION
**Pull request by FeaXR**
Addressed #73, should also solve #67

### CODE REVIEW

**Comment by FeaXR** [comment]
@solymosi 
This PR contains the same changes as #74  but also the fix for #73

**Comment by solymosi** [comment]
Thanks for the PR 🎉 – before I review, could you please squash all these 14 commits into a single one?

**Comment by FeaXR** [comment]
Squashed

**Comment by FeaXR** [comment]
@solymosi I think this should do it. I tested it a bit and seems to work

**Comment by solymosi** [comment]
Now that #74 was merged, can you please rebase this against `master`? Then I can merge this one as well.

**Comment by solymosi** [comment]
Nevermind, I've included this in a slightly different way in the latest release.

**Pull request closed without merging**
