### PR TITLE
Remove unneccessary subject rows from exam search dropdown when subject has no exam available

### PR DESCRIPTION
**Pull request by whisperity**
As per discussed earlier in #1 and #5.

This request should cover everything, now in a less flickery and even more optimised way.

---

As an added extra, the row colouring is also introduced in the listbox itself. This has the increased advantage of you seeing (in case you missed or didn't even receieve the "New exam was posted for one of your subjects" letter) if there's a subject you did not attempt an exam from and _now you can_.

### CODE REVIEW

**Comment by whisperity** [comment]
Now that exam allocation has yet again started in a new semester, will we return to this pull request? :smile:

**Comment by solymosi** [comment]
I don't think this behavior below is correct; all 3 subjects are supposed to show up in the list, right?

image

I still feel a bit uneasy about shipping this feature in its current state, because the downside of a bug here is significantly larger (inability to select certain subjects because they are missing) than the upside of a bug-free operation (easier navigation of the subject list).

I'll investigate the changes and try to figure out how to make the code more resilient to unexpected scenarios. It's better not to hide something that should be hidden than to hide something that shouldn't be.

**Comment by solymosi** [comment]
Superseded by #11

**Comment by whisperity** [comment]
I think if you merge #11, this pull request will also be marked as _Merged_. Could you please reopen?

**Comment by solymosi** [comment]
Might be... let's try 😄

**Comment by solymosi** [comment]
Ha, apparently Github is smart like that 👍

**Comment by whisperity** [comment]
[OFF]
Yep. :slightly_smiling_face: (Just you cannot mark a PR _merged_ by hand (which is ugly I think) if you, as a maintainer, rebase or fix-up some commits...)

**Comment by solymosi** [comment]
This new feature looks really cool, thanks again for implementing it, and for having the patience to figure out how the existing code works and where the new code should go 👍 

I have a long overdue plan in place to clean up the code of the script and make it more modular, because right now it's kind of a mess (which tends to happen to organically grown projects). Once I get around to doing that, hopefully new features will become much easier to add, without requiring too much "insider knowledge" of how the rest of the script works, so I won't need to fix up newly contributed code that much.

I'll write up an issue for the cleanup, just in case I happen have some free time in the near future.

**Comment by whisperity** [comment]
:wink: :beers:
But make sure you put a release up to the download site! And yeah, I know big projects and how messy they get.

**Comment by solymosi** [comment]
The release will go out today 🎉 

Created an issue for the code cleanup: #12. If you have any ideas other than the ones I listed, please leave a comment.

**Pull request merged**
