### PR TITLE
Remove saved logins feature because Neptun no longer prevents browsers from saving login credentials

### PR DESCRIPTION
**Pull request by gergoradeczki**
Szerintem rohadt idegesítő, hogy minden egyes bejelentkezésnél megkérdezi, hogy 
_"Szeretnéd menteni a beírt adatokat, hogy később egy kattintással be tudj lépni erről a számítógépről?"_.
Másfelől meg konkrétan olvasható szövegként menti el a JELSZAVAD. WTF.

Egy rendes böngésző elintézi neked a bejelentkezési adatok mentését.

### CODE REVIEW

**Comment by solymosi** [comment]
At the time this feature of the script was initially released Neptun used to actively block browsers from saving the login credentials. Apparently this is no longer the case so we can indeed remove this feature to eliminate the risk of passwords getting leaked.

However, we need to do this the right way instead of just commenting all this stuff out. Also, the autologin feature should still remain so it will need to detect if the browser has auto-filled the login credentials and auto-submit the form.

Also, even if we remove this feature we need to make sure that the next update actually clears the login credentials from the local storage for existing users.

**Comment by gergoradeczki** [comment]
Thank you Solymosi, very cool.

**Comment by gergoradeczki** [comment]
Accidentally closed this pull request.

You are right. The script needs a function that makes sure every login details have been removed.

**Comment by solymosi** [comment]
> Also, the autologin feature should still remain so it will need to detect if the browser has auto-filled the login credentials and auto-submit the form.

Unfortunately the browsers' security model does not allow scripts to programmatically submit autofilled forms unless the user interacts with the page first (for security reasons). Which means that the stored passwords feature will _have_ to stay if we want to keep the autologin feature 😢 

What we can do here is:
* update the popup to include a "don't ask me again" checkbox
* add a huge warning that tells users _not_ to use the feature on a shared or unprotected computer

**Comment by whisperity** [comment]
Also, the saving was one in B64, not plaintext, I think. Did moving from Grease to Tampermoney break this?

**Comment by solymosi** [comment]
@whisperity It is still base64. Granted, that is not much better than plain text.

**Comment by whisperity** [comment]
Okay so how to move forward with this? If the autologin feature is needed (which is broken on ELTE Neptun so far...), we have to keep doing the save thing. So perhaps the following is the right way forward:
 - for each install and for each unique Neptun URL, ask the user at the **first** opening **once** whether they want automatic login and saving of credentials
 - save this response somewhere
 - if yes, save every password and login whatsoever, and do the auto login as is... (*)
 - if no, turn the entire stuff off and never ask again
 - show some button on the login page in case of the `No` option that throws away the `No` save and asks the user again

(*): There's also an issue with *which* Neptun ID we are auto logging in with... I think so far it always chooses the first, i.e. oldest, saved data?

And this new-ish logic above with the changes to handle the ELTE homepage form #53 properly could be kept too...

**Comment by whisperity** [comment]
Also, is there a "secure storage" or something in browsers, where addons and sites could save thing but the browser stores it encrypted with some local key? The thing could be moved there. We can't afford any additional cryptography either way, because if we provide a key, it will be on the machine still, so it can be hacked. If we do remote encryption, then passwords are sent to random servers, which is even worse...

**Comment by solymosi** [comment]
I did some thinking and I believe I may have a solution here.

Auto-login is only really useful if Neptun kicks you out unexpectedly while you're standing by waiting for signups to open – i.e. in scenarios where you may not immediately realize that you've been logged out. When you _first_ log in, you don't _really_ need auto-login, you can just as easily click the button yourself once your browser has auto-filled your credentials.

So how about this:

* Upon the first login to Neptun in a particular browser tab, when the user clicks on the login button, we save their credentials to the _session storage_ of the browser. Session storage is tied to the tab itself and is cleared when the tab is closed, so this way credentials are only stored temporarily.
* Should the user end up on the login screen again in the same tab, we automatically log them back in with the stored credentials.
* If the user uses the logout button to log out, we clear the stored credentials to prevent an auto-login afterwards.
* To make reading out the credentials from the session storage harder, we can encrypt them and store the encryption key in TamperMonkey's long-term storage.

This way we would still get auto-login when it matters, but we wouldn't be storing Neptun credentials long-term, unencrypted.

I'll try to implement this sometime in the following weeks.

**Pull request closed without merging**
